language: php
php:
  - 7.1.9
before_install:
- sudo apt update
- sudo apt install apache2 #nodejs
- yarn add headless-chrome-crawler #async
#- curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
#- sudo apt-get install -y nodejs
#- which node
#- which nodejs
#- ls -la `which node`
#- ls -la /usr/bin/node
#- nodebin=$(which node)
#- sudo rm "$nodebin" /usr/bin/node
#- sudo ln -s /usr/bin/nodejs "$nodebin"
- sudo a2enmod headers proxy_http
- printf "Listen 8080" | sudo tee /etc/apache2/ports.conf
- printf "ProxyPass \"/\" \"http://localhost:8081\"\nProxyPassReverse \"/\" \"http://localhost:8081\"" | sudo tee /etc/apache2/conf-available/csp.conf
- cat csp.conf | sudo tee -a /etc/apache2/conf-available/csp.conf
- sudo a2enconf csp.conf
- sudo service apache2 restart
- nodejs -v
- node -v
#- sudo npm config set ca null
#- yarn install --ignore-engines headless-chrome-crawler
#- npm install async
script: chmod +x build.sh && ./build.sh
